"""Abstract store interface for managing schemas, scenarios, executions, and reports.

All store backends (InMemoryStore, SQLiteStore) must implement this Protocol
to ensure interface consistency and enable dependency injection.
"""

from __future__ import annotations

from typing import AsyncIterator, Protocol, runtime_checkable

from api_chaos_agent.models.schema import APISpec
from api_chaos_agent.models.scenario import ChaosScenario
from api_chaos_agent.models.report import TestResult, Report


@runtime_checkable
class StoreProtocol(Protocol):
    """Protocol defining the contract for all store backends.

    Every store implementation must provide these methods with matching
    signatures so that routers and services can depend on the Protocol
    rather than a concrete class.
    """

    async def save_schema(self, spec: APISpec) -> str: ...
    async def get_schema(self, schema_id: str) -> APISpec | None: ...
    async def list_schemas(self, offset: int = 0, limit: int = 100) -> dict[str, APISpec]: ...
    async def save_scenario(self, scenario: ChaosScenario) -> str: ...
    async def get_scenario(self, scenario_id: str) -> ChaosScenario | None: ...
    async def list_scenarios(self, offset: int = 0, limit: int = 100) -> dict[str, ChaosScenario]: ...
    async def save_execution(self, result: TestResult) -> str: ...
    async def get_execution(self, execution_id: str) -> TestResult | None: ...
    async def list_executions(self, offset: int = 0, limit: int = 100) -> dict[str, TestResult]: ...
    async def save_report(self, report: Report) -> str: ...
    async def get_report(self, report_id: str) -> Report | None: ...
    async def list_reports(self, offset: int = 0, limit: int = 100) -> dict[str, Report]: ...
    async def clear(self) -> None: ...
    async def stats(self) -> dict[str, int]: ...
